GG-Studio-990001/Grayed-Game

Assets/Plugins/Editor Default Resources.meta
Assets/Plugins/Editor Default Resources/Febucci.meta
Assets/Plugins/Editor Default Resources/Febucci/HierarchyData.asset
Assets/Plugins/Editor Default Resources/Febucci/HierarchyData.asset.meta
Packages/manifest.json
Packages/packages-lock.json
ProjectSettings/ProjectSettings.asset

Feat: Add Custom Hierarchy Lib

---

.idea/.idea.GameOver/.idea/workspace.xml
Assets/Plugins/Febucci/Text Animator/Extra/Typewriter Sound - Package.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations/PlayMaker - Integration.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations/Visual Scripting - Integration.unitypackage.meta
Assets/Scripts/Runtime/CH1/Main/PlayerFunction/TopDownMovement.cs
Assets/Scripts/Runtime/CH1/Main/TopDownPlayer.cs
Assets/Scripts/Tests/Runtime/DialogueUITests.cs
Assets/Scripts/Tests/Runtime/SettingsUITests.cs

Top down player refactor

---

.idea/.idea.GameOver/.idea/workspace.xml
Assets/Scripts/Runtime/CH1/Main/PlayerFunction/TopDownAnimation.cs
Assets/Scripts/Runtime/CH1/Main/PlayerFunction/TopDownMovement.cs
Assets/Scripts/Runtime/CH1/Main/TopDownPlayer.cs
Assets/Scripts/Runtime/ETC.meta
Assets/Scripts/Runtime/ETC/Const.cs
Assets/Scripts/Runtime/ETC/Const.cs.meta
Assets/Scripts/Runtime/ETC/Enums.cs
Assets/Scripts/Runtime/ETC/Enums.cs.meta
Assets/Scripts/Tests/Runtime/SettingsUITests.cs
Assets/Scripts/Tests/Runtime/TopDownPlayerTests.cs

176 feat msc01 charter

---

.idea/.idea.GameOver/.idea/workspace.xml
Assets/Scenes/TopDownTest.unity
Assets/Scripts/Runtime/Common/Presentation/SettingsUIPresenter.cs
Assets/Scripts/Runtime/Common/View/SettingsUIView.cs
Assets/Scripts/Tests/Runtime/SettingsUITests.cs

종료 버튼 만들다가 조금 더 유연하게 구조를 수정해봤습니다..?

Feat: Exit Button and Refactor Setting Ui

---

.idea/.idea.GameOver/.idea/workspace.xml
Assets/Scenes/TopDownTest.unity
Assets/Scripts/Runtime/CH1/Main/Ch1GameController.cs
Assets/Scripts/Runtime/CH1/Main/TopDownPlayer.cs
Assets/Scripts/Runtime/Common/View/SettingsUIView.cs

모든 키 설정을 연동하기 위해서 `GameOverControls` input system 객체를 하나로 만들어야 해서 일단 싱글톤으로 작업했습니다.
이후 이 부분이 서비스 로케이터로 가든 DI로 빠지든 리팩터링을 해야할 것 같은데 가장 중요한 점은 키 입력을 하나로 관리할 친구가 필요하다는 점인 것 같습니다.
일단 Player, UI Input에 따라 구분될 수 있게 작업은 했습니다!

Feat: Input system union Object

---

Assets/Resources/Sample.meta
Assets/Scripts/Runtime/CH1/Main/PlayerFunction/TopDownAnimation.cs

Refactor-MainSystem_02

---

Assets/Presets/AddressableAssetsData/AssetGroups/Default Local Group.asset
Assets/Scenes/TopDownTest.unity
Assets/Timeline.meta
Assets/Timeline/CutScene.playable
Assets/Timeline/CutScene.playable.meta
Assets/Timeline/DisableSignal.signal
Assets/Timeline/DisableSignal.signal.meta
Assets/Timeline/EnableSignal.signal
Assets/Timeline/EnableSignal.signal.meta
Assets/TimelineTest.cs
Assets/TimelineTest.cs.meta
Packages/manifest.json
Packages/packages-lock.json

타임라인 패키지 추가했습니다.
임시로 기능들 몇 가지 추가하고 만들어봤는데 이후에 연출에 사용할 것 같습니다.

Feat: Timeline

---

Assets/Plugins/LimitlessUnityDevelopment/LimitlessUnityDevelopment/Retro Look Pro URP/Scripts/Editor/ColormapPalette_RLPRO_URP_Editor.cs
Assets/Plugins/LimitlessUnityDevelopment/LimitlessUnityDevelopment/Retro Look Pro URP/Scripts/RetroLook.asmdef
Assets/Presets/AddressableAssetsData/link.xml
Assets/Presets/AddressableAssetsData/link.xml.meta
Assets/Presets/Data/PlayerData.asset
ProjectSettings/ProjectSettings.asset

Build Bug Fix

---

Assets/Plugins/LimitlessUnityDevelopment/LimitlessUnityDevelopment/Retro Look Pro URP/Example Scenes/Resources/RLPro_ForwardRenderer.asset
Assets/Scenes/CH1.unity
Assets/Scripts/Runtime/CH1/SubB/3 Match/ThreeMatchPuzzleClearCheck.cs
Assets/Scripts/Runtime/CH1/SubB/3 Match/ThreeMatchPuzzleClearCheck.cs.meta
Assets/Scripts/Runtime/CH1/SubB/3 Match/ThreeMatchPuzzleController.cs
Assets/Scripts/Runtime/CH1/SubB/3 Match/ThreeMatchPuzzleLogic.cs
Assets/Scripts/Runtime/Manager/DataManager.cs
Assets/_CH1/Arts/Animations/SubB/TypeA_Effect.anim
Assets/_CH1/Arts/Animations/SubB/TypeB_Effect.anim
Assets/_CH1/Arts/Animations/SubB/TypeC_Effect.anim
Assets/_CH1/Arts/Animations/SubB/TypeD_Effect.anim

24-05-15 추가 작업
스테이지 1, 3 Mover 위치 변경 (맵에 걸리게)
puzzle match sound 타이밍 수정
스테이지 3 럭키 OnActive 때 터지게
3Match puzlle clear data save

406 ch1 튜토리얼 캔디 크러시 사가 구체화

---

Assets/Scenes/CH1.unity
Assets/Scenes/Pacmom.unity
Assets/Scripts/Runtime/CH1/Main/Dialogue/Ch1DialogueController.cs
Assets/Scripts/Runtime/CH1/Main/Dialogue/CutSceneDialogue.cs
Assets/Scripts/Runtime/CH1/Main/Npc/NpcPosition.cs
Assets/Scripts/Runtime/CH1/Main/Player/TopDownPlayer.cs
Assets/Scripts/Runtime/CH1/Pacmom/PMEnding.cs
Assets/Scripts/Runtime/Input/InGameKeyBinder.cs
Assets/Scripts/Runtime/Manager/DataManager.cs
Assets/Scripts/Runtime/Manager/SoundManager.cs
Assets/_CH1/Arts/Sprites/SubB/SLG/SLGObject.png.meta
Assets/_CH1/Dialogues/Mamago.yarn

럭키 버그 빼고 완료..
(사실 럭키 버그 찾기만 하고 코드 기능 추가는 딱히 없음..)
이슈 참고

[CH1] 보완 개발 2차-3

---

Assets/Scenes/CH1.unity

FIx : Retargetting Image Sprite

---

Assets/Scenes/CH1.unity
Assets/Scripts/Runtime/CH1/SubB/SLG/SLGActionComponent.cs

Feat : Add Resource Gain Anim

---

Assets/Scripts/Runtime/CH1/Main/Dialogue/CutSceneDialogue.cs
Assets/Scripts/Runtime/CH1/SubB/SLG/SLGActionComponent.cs
Assets/Scripts/Runtime/CH1/SubB/SLG/SLGInteractionObject.cs

- const 변수 네이밍 방식 수정
- warning 뜨던 이슈 수정
- 우연님 요청대로 연출 끝난 후 상태 변경하도록 수정
(연출 나오고 , 연출 진행 후에 상태 넘어가는것 확인했습니다.)

Ch1 slg refactoring

---

Assets/Scripts/Runtime/CH1/SubB/SLG/SLGActionComponent.cs

Feat : Change Anim Ease Graph

---

Assets/Plugins/Febucci/Text Animator/Extra/Typewriter Sound - Package.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations/PlayMaker - Integration.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations/Visual Scripting - Integration.unitypackage.meta
Assets/Scenes/CH1.unity
Assets/Scripts/Runtime/CH1/SubB/3 Match/Jewelry.cs
Assets/Scripts/Runtime/CH1/SubB/3 Match/ThreeMatchPuzzleController.cs
Assets/Scripts/Runtime/CH1/SubB/3 Match/ThreeMatchPuzzleStageData.cs
Assets/Scripts/Runtime/CH1/SubB/3 Match/ThreeMatchPuzzleStageData.cs.meta
Assets/Scripts/Runtime/Manager/DataManager.cs
Assets/StreamingAssets/build_info

Fix: 3M Data Load

---

Assets/Plugins/Febucci/Text Animator/Extra/Typewriter Sound - Package.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations/PlayMaker - Integration.unitypackage.meta
Assets/Plugins/Febucci/Text Animator/Integrations/Visual Scripting - Integration.unitypackage.meta
Assets/Scenes/CH1.unity
Assets/Scripts/Runtime/CH1/SubB/3 Match/Jewelry.cs
Assets/StreamingAssets/build_info

FIx: 3M (Lucky)

---

Assets/Plugins/Febucci/Text Animator/Data/Appearances/SizeAppearance.asset
Assets/Plugins/Febucci/Text Animator/Data/Behaviors/BounceBehavior.asset
Assets/Plugins/Febucci/Text Animator/Data/Behaviors/ShakeBehavior.asset
Assets/Plugins/Febucci/Text Animator/Data/Behaviors/SizeBehavior.asset
Assets/Plugins/Febucci/Text Animator/Data/Behaviors/SlideBehavior.asset
Assets/Plugins/Febucci/Text Animator/Data/Behaviors/WaveBehavior.asset
Assets/Plugins/Febucci/Text Animator/Data/Resources/TextAnimatorSettings.asset
Assets/Scenes/CH1.unity
Assets/Scenes/Pacmom.unity
Assets/StreamingAssets/build_info
Assets/_CH1/LuckyDialogues/3Match.yarn
Assets/_CH1/LuckyDialogues/Meet.yarn
Assets/_CH1/LuckyDialogues/Slg.yarn
Assets/_CH1/_Pacmom/Dialogues/Lucky_Pacmom.yarn
Assets/_CH1/_Pacmom/Dialogues/PacmomDialogue.yarn

팩맘, 럭키 텍스트 애니메이션 적용

---

Assets/_CH1/Arts/Sprites/SubB/SLG/SLG_Cursor.png.meta

Fix : Cursor Should Be Readable

---

Assets/Scenes/SuperArio.unity
Assets/Scripts/Runtime/CH2/SuperArio/Ario.cs
Assets/Scripts/Runtime/CH2/SuperArio/ArioManager.cs
Assets/Scripts/Runtime/CH2/SuperArio/ArioStore.cs
Assets/Scripts/Runtime/CH2/SuperArio/ArioUIController.cs
Assets/Scripts/Runtime/CH2/SuperArio/BGScrolling.cs
Assets/Scripts/Runtime/CH2/SuperArio/HeartBox.cs
Assets/Scripts/Runtime/CH2/SuperArio/HeartBox.cs.meta
Assets/Scripts/Runtime/CH2/SuperArio/IStoreBox.cs
Assets/Scripts/Runtime/CH2/SuperArio/IStoreBox.cs.meta
Assets/Scripts/Runtime/CH2/SuperArio/Mario.cs
Assets/Scripts/Runtime/CH2/SuperArio/ObstacleBase.cs
Assets/Scripts/Runtime/CH2/SuperArio/ObstacleManager.cs
Assets/Scripts/Runtime/CH2/SuperArio/SAKeyBinder.cs
Assets/Scripts/Runtime/CH2/SuperArio/StoreWall.cs
Assets/Scripts/Runtime/CH2/SuperArio/StoreWall.cs.meta
Assets/Scripts/Runtime/Input/InGameKeyBinder.cs
ProjectSettings/ProjectSettings.asset

[CH2] 접속 게임 - 슈퍼 아리오 브라더스

---

Assets/Scenes/CH1.unity
Assets/Scripts/Runtime/CH1/Main/Dialogue/CutSceneDialogue.cs
Assets/_CH1/Dialogues/Pack.yarn

Pack 얻고난 후에 Position Set 하도록 수정

Fix : Set Position After Equipping Translator Pack

---

Assets/Scenes/SuperArio.unity
Assets/Scripts/Runtime/CH2/SuperArio/ArioManager.cs
Assets/Scripts/Runtime/CH2/SuperArio/ArioReward.cs
Assets/Scripts/Runtime/CH2/SuperArio/GroundScrolling.cs
Assets/Scripts/Runtime/CH2/SuperArio/NPC.cs
Assets/Scripts/Runtime/CH2/SuperArio/NPC.cs.meta
Assets/Scripts/Runtime/CH2/SuperArio/ObstacleManager.cs
Assets/Scripts/Runtime/CH2/SuperArio/ObstacleSpawnDataSet.asset
Assets/Scripts/Runtime/CH2/SuperArio/RewardPipe.cs
Assets/Scripts/Runtime/CH2/SuperArio/RewardPipe.cs.meta
Assets/_CH2/ArioDialogues.meta
Assets/_CH2/ArioDialogues/NPC1.yarn
Assets/_CH2/ArioDialogues/NPC1.yarn.meta
Assets/_CH2/ArioDialogues/SuperArio.yarnproject
Assets/_CH2/ArioDialogues/SuperArio.yarnproject.meta
Assets/_CH2/_SuperArio/Building.prefab

[CH2] 접속 게임 - 슈퍼 아리오 브라더스 (8)

---

Assets/CameraLetterBox.cs
Assets/CameraLetterBox.cs.meta
Assets/Scenes/SuperArio.unity
Assets/Scripts/Runtime/CH2/SuperArio/ArioStore.cs
Assets/Scripts/Runtime/CH2/SuperArio/ObstacleManager.cs
Assets/Scripts/Runtime/CH2/SuperArio/StoreBoxPhysics2D.physicsMaterial2D
Assets/Scripts/Runtime/CH2/SuperArio/StoreBoxPhysics2D.physicsMaterial2D.meta
Assets/Scripts/Runtime/Input/InGameKeyBinder.cs
Assets/_CH2/_SuperArio/VolumeProfiles.meta
Assets/_CH2/_SuperArio/VolumeProfiles/SuperArio Post-processing volume.asset
Assets/_CH2/_SuperArio/VolumeProfiles/SuperArio Post-processing volume.asset.meta

Ch2 접속 게임 슈퍼 아리오 브라더스 9

---

Assets/Scenes/Dancepace.unity
Assets/Scripts/Runtime/CH3/Dancepace/Characters/DPRapley.cs
Assets/Scripts/Runtime/CH3/Dancepace/Effects/HeartEffect.cs
Assets/Scripts/Runtime/CH3/Dancepace/Managers/DPEffectManager.cs
Assets/Scripts/Runtime/CH3/Dancepace/Managers/DPKeyBinder.cs
Assets/Scripts/Runtime/CH3/Dancepace/Managers/DPManager.cs
Assets/Scripts/Runtime/CH3/Dancepace/Managers/DPUIManager.cs
Assets/Scripts/Runtime/CH3/Dancepace/UI/KeyGuideUI.cs
Assets/Scripts/Runtime/CH3/Dancepace/UI/TimeBarUI.cs
Assets/Scripts/Runtime/Input/InGameKeyBinder.cs
Assets/StreamingAssets/build_info

- KeyGuide 오류 수정
- TimeBar 로직 변경
- 플레이 루프 오류 변경
- 비트 입력 타이밍 수정
- 랜덤 비트 출력 기능
- 게임 종료 조건 추가

ch3 접속게임 dancepace 프로토타입 개발
